// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQuanLyDuAn.Data;

#nullable disable

namespace WebQuanLyDuAn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525020117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebQuanLyDuAn.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xây dựng nền tảng bán hàng online cho công ty.",
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerName = "Nguyễn Văn An",
                            Name = "Website Thương Mại Điện Tử",
                            Priority = 2,
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ứng dụng mobile quản lý chấm công và lương.",
                            EndDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerName = "Trần Thị Bình",
                            Name = "App Quản Lý Nhân Sự",
                            Priority = 1,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dashboard phân tích dữ liệu kinh doanh.",
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerName = "Lê Minh Châu",
                            Name = "Hệ Thống Báo Cáo BI",
                            Priority = 3,
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        });
                });

            modelBuilder.Entity("WebQuanLyDuAn.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Phạm Văn D",
                            DueDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 2,
                            Title = "Thiết kế giao diện trang chủ"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Nguyễn Thị E",
                            DueDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Xây dựng API giỏ hàng"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Trần Văn F",
                            DueDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 3,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Tích hợp cổng thanh toán"
                        },
                        new
                        {
                            Id = 4,
                            AssignedTo = "Lê Thị G",
                            DueDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Phân tích yêu cầu hệ thống"
                        },
                        new
                        {
                            Id = 5,
                            AssignedTo = "Hoàng Văn H",
                            DueDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Thiết kế database nhân sự"
                        },
                        new
                        {
                            Id = 6,
                            AssignedTo = "Vũ Thị I",
                            DueDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 3,
                            ProjectId = 3,
                            Status = 2,
                            Title = "Kết nối nguồn dữ liệu ERP"
                        });
                });

            modelBuilder.Entity("WebQuanLyDuAn.Models.ProjectTask", b =>
                {
                    b.HasOne("WebQuanLyDuAn.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
